# Generated by Django 3.2 on 2021-08-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Открытый'), ('in_progress', 'В обработке'), ('canceled', 'Отменённый'), ('finished', 'Завершённый')], max_length=20),
        ),
    ]
